passed: 0, failed: 0, errored: 1
fregot.tests.invalid.stack_trace_01.test_stack_trace:
fregot (eval error):
  "stack-trace-01.rego" (line 5, column 3):
  builtin type error:

    5|   x + input.msg with input as {"msg": "crash"}
         ^^^^^^^^^^^^^

  Expected number but got string

  Stack trace:
    rule fregot.tests.invalid.stack_trace_01.rule1 at stack-trace-01.rego:9:3
    rule fregot.tests.invalid.stack_trace_01.rule2 at stack-trace-01.rego:13:3
    rule fregot.tests.invalid.stack_trace_01.rule3 at stack-trace-01.rego:17:3
    rule fregot.tests.invalid.stack_trace_01.test_stack_trace at tests:1:1
